### ISSUE TITLE
Nodester errors have zero details

### ISSUE THREAD

**Issue by mcandre** [nodester/nodester-cli#10]
```
$ nodester app init doesnodework
nodester info clone complete
nodester info writing app data to config
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERRO false
```

How am I supposed to debug that?

**Comment by nodester** [comment]
A few of us are having the same issue at the moment.  I have opened the
following ticket to track the status:
https://github.com/nodester/nodester/issues/96

Regards,
Chris

**Comment by yocontra** [comment]
AFAIK This has been fixed, closing it.
