### ISSUE TITLE
nodester app create - no error info when app exists

### ISSUE THREAD

**Issue by EvanBurchard** [nodester/nodester-cli#11]
So it's fairly obvious why this fails, but as it will be a likely first experience for people to try example code, it might be worth guiding this experience a bit more.  Also, since there is no way to check whether a project name has been taken through the cli, non cargo culters who enter their app name without copy/pasting could also run into this issue.  

I think an error message such as "[app name] has already been taken.  Please select a new app name," would be really helpful.  

Reproducing:
$ nodester app create myapp hello.js  
nodester info creating app: myapp hello.js  
nodester ERRO failure

**Comment by adrusi** [comment]
I agree. it had me really confused as to what the error was

**Comment by chrismatthieu** [comment]
Not sure how to deploy the update CLI to NPM

**Comment by yocontra** [comment]
It's npm publish from the directory of the package. You need credentials for the package though (whoever created it should have them)
