### ISSUE TITLE
nodester command not found

### ISSUE THREAD

**Issue by ghost** [nodester/nodester-cli#13]
I am a newbie.

I installed nodester-cli using npm on ubuntu 11.04 beta. When I write "nodester" I get "command not found"
node --version: v0.5.0-pre
npm --version: 1.0.1rc9

Any ideas?

**Comment by davglass** [comment]
If you are using npm 1 (which you shouldn't be if you are a newbie), then you need to install the cli with the `-g` flag to force it to install globally.

**Comment by ghost** [comment]
Thanks #davglass. It's working now.
I just followed the official instructions how to install NPM. Didn't put much thought into which version is installed. I didn't see the common stable vs. development options.
