### ISSUE TITLE
Issues with 'nodester app init' under Ubuntu (Bad file descriptor)

### ISSUE THREAD

**Issue by cjoudrey** [nodester/nodester-cli#2]
This might be a problem on my end, but there seems to be a problem with 'app init'. It's failing to create the folder.

```
cjoudrey@duo:~/Web$ nodester app init mynodesterapp3 ./mynodesterapp3

fs.js:184
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor './mynodesterapp3/.nodester.appconfig'
    at Object.openSync (fs.js:184:18)
    at Object.writeFileSync (fs.js:436:15)
    at /usr/local/lib/node/.npm/nodester-cli/0.1.7/package/bin/nodester.js:274:16
    at ChildProcess.exithandler (child_process.js:85:7)
    at ChildProcess.emit (events.js:45:17)
    at ChildProcess.onexit (child_process.js:171:12)
```

I tried creating the folder manually, but it still crashes at the same spot with an extra error message 'file exists'.

**Comment by cjoudrey** [comment]
Managed to get it working by creating the directory myself and running the command in the directory:

```
cjoudrey@duo:~/Web/mynodesterapp3$ nodester app init mynodesterapp3 .
Error: EEXIST, File exists '.'
false
cjoudrey@duo:~/Web/mynodesterapp3$
```

**Comment by cjoudrey** [comment]
After further investigation with Chris, we noticed the script is actually failing to create the project directory: `fs.mkdirSync(folder, 0750)`. Strangely enough, an exception is not thrown. It silently fails to create the folder, then all calls to `fs.writeFileSync(folder, ...` fail because the folder does not exist.

**Comment by cjoudrey** [comment]
The issue may be linked to a bad RSA pub key.

**Comment by cschram** [comment]
I'm also having the same issue. I also can't add git repo's for Nodester apps:

git remote add nodester ec2-user@nodester.com:/home/ec2-user/hosted_apps/coreyschram/356-32156eccee37de8816cd4bd9feeecfee.git
fatal: Not a git repository (or any of the parent directories): .git

**Comment by cjoudrey** [comment]
Make sure you run the `git remote add nodester ...` inside the app folder.

**Comment by cschram** [comment]
Alright, got it figured out. I'm just not good with git, I'm used to using Mercurial :p

**Comment by volpe** [comment]
Same issue as cjoudrey.  Seems it isn't creating the project directory but is still trying to write the file inside it.

I'm on OS X 10.6.6/node 0.4.1

**Comment by cjoudrey** [comment]
This problem was caused by a bad SSH key in my case. I simply generated a new key and it worked.

**Comment by chrismatthieu** [comment]
I believe this issue is related to nodester #11 and is caused by a bad key on file or a passphrase in the key.  This issue is being tracked on the following ticket:

https://github.com/nodester/nodester/issues/101

**Comment by yocontra** [comment]
I pushed an update that fixes this. Update to the latest CLI
