### ISSUE TITLE
npm install outputs error

### ISSUE THREAD

**Issue by tracend** [nodester/nodester-cli#23]
When I try to install a module through the "nodester" commands I get an error

In particular in "lib/npm.js" and in line 41
                              if (l[1].toLowerCase() === 'warn') {

cannot call method toLowerCase of undefined

Above that there is a condition which obviously isn't enough: 

if (l[1]) { 

As a suggestion please try this instead

if ('1' in l) { 

Or even a try{} catch {} could do...

**Comment by DanBUK** [comment]
tracend are you sure you're on the most recent version of nodester-cli I thought I fixed that a week or more ago.

**Comment by tracend** [comment]
You are right sir - hadn't updated the cli for a while. 

Did some tests installing packages with no further issues
