### ISSUE TITLE
nodester ERROR [HTTP 401] failure

### ISSUE THREAD

**Issue by wesbos** [nodester/nodester-cli#24]
Just got my Nodester account and I'm getting this error when I try to `nodester user account u p`

nodester info verifying credentials
nodester ERROR [HTTP 401] failure

Any idea why?

**Comment by yocontra** [comment]
Did you use any special characters in your username or password?

**Comment by wesbos** [comment]
just uppercase, lowercase and numbers..

**Comment by yocontra** [comment]
Are you still having this issue? We've changed a lot in the cli and server lately and may have fixed it

**Comment by wesbos** [comment]
Signed up again and everything is working swimmingly. Thanks guys :)
