### ISSUE TITLE
fatal: write error: No space left on device

### ISSUE THREAD

**Issue by bryanbcheng** [nodester/nodester-cli#25]
I just started having this issue today, but when I tried pushing my app to nodester, it gave me a fatal error saying there "write error: No space left on device". I'm wondering is there a limit to the size of our project?

I fixed it temporarily when I noticed npm had installed several modules that I did not want, so after removing it, it worked for a while. Now it's giving me the same error when I try to push.

**Comment by yocontra** [comment]
How much space are you using?

**Comment by bryanbcheng** [comment]
Originally 14mb but I took out the local node_modules which was 6.6mb.

**Comment by bryanbcheng** [comment]
I also had a problem trying to delete my app, figuring I would delete it and recreate it, but it gave me a nodester ERROR socket hang up

I also tried nodester app create nodester app init and pushing that and it gives me the same error. I'm wondering is there a limit to how much I can push per account and if my previous apps are still taking up space?

**Comment by DanBUK** [comment]
We had some issues server side that was affecting this. But it's hopefully fixed now.

Please re-test.
