### ISSUE TITLE
The clone CLI command return a 'Hello World' server

### ISSUE THREAD

**Issue by alejandro** [nodester/nodester-cli#27]
Hello guys. I'm open this issues in order to this [tweet](http://twitter.com/Nodester/status/109416070158356480?iid=am-111949529413149217988416481&nid=4+status_timestamp&uid=53717698). In the last days I reinstall my OS, I'm running now Ubuntu 11.04 (Don't ask why). I install all, nodejs, npm and the nodester CLI. I setup everything again, my Public KEY, email, password... I'm able to create new apps, logs, etc. But when I'm trying to clone a previous app, with this command:
`nodester app clone APP_NAME`

And this the trace:

```
    nodester info initializing git repo for APP_NAME into folder APP_NAME
    nodester info cloning the repo git clone git@nodester.com:/node/git/alejandromg/APP_NAME.git APP_NAME
   nodester info Writing app data to config in APP_NAME/.nodester.appconfig
```

I get a a simple `Hello World` server as response,  like the one in the documetation of nodejs. Other times it's just return nothing. 

System, if it's need it:
nodejs: `v0.4.11`
npm: `1.0.27`
nodester: `0.2.20`

**Comment by yocontra** [comment]
What's the name of your app?
