### ISSUE TITLE
Reopening "No space left on device" issue

### ISSUE THREAD

**Issue by stevebrownlee** [nodester/nodester-cli#28]
Hey guys, set up my environment this morning (thanks for the invite), and going through the steps.  When I hit the part about installing a module for my app, I tried installing Now, and got the following error during installation.
# 

nodester info installing to app: redacted
nodester info installing these npm packages: now
nodester > node-proxy@0.4.0 install /node/app/redacted/3550-525aa2e1aa83ea228e10d6c905de4d0b_rw/node_modules/now/node_modules/node-proxy
nodester > make
nodester BUILDING: C++ Component
nodester Checking for program g++ or c++          : /usr/bin/g++ 
nodester Checking for program cpp                 : /usr/bin/cpp 
nodester Checking for program ar                  : /usr/bin/ar 
nodester Checking for program ranlib              : /usr/bin/ranlib 
nodester Checking for g++                         : ok  
nodester Checking for node path                   : not found 
nodester Checking for node prefix                 : ok /usr 
nodester 'configure' finished successfully (0.036s)
nodester Waf: Entering directory `/node/app/redacted/3550-525aa2e1aa83ea228e10d6c905de4d0b_rw/node_modules/now/node_modules/node-proxy/src/build'
nodester [1/2] cxx: node-proxy.cc -> build/default/node-proxy_1.o
nodester ../node-proxy.cc:1573: fatal error: error writing to /tmp/cchRi4RU.s: No space left on device
nodester compilation terminated.
nodester Waf: Leaving directory`/node/app/redacted/3550-525aa2e1aa83ea228e10d6c905de4d0b_rw/node_modules/now/node_modules/node-proxy/src/build'
nodester Build failed:  -> task failed (err #1): 
nodester    {task: cxx node-proxy.cc -> node-proxy_1.o}
nodester cp: cannot stat `src/build/default/node-proxy.node': No such file or directory
nodester make: *** [all] Error 1
nodester npm ERR! error installing node-proxy@0.4.0 Error: node-proxy@0.4.0 install:`make`
nodester npm ERR! error installing node-proxy@0.4.0`sh "-c" "make"`failed with 2
nodester npm ERR! error installing node-proxy@0.4.0     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing node-proxy@0.4.0     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing node-proxy@0.4.0     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! error installing now@0.7.0 Error: node-proxy@0.4.0 install:`make`
nodester npm ERR! error installing now@0.7.0`sh "-c" "make"`failed with 2
nodester npm ERR! error installing now@0.7.0     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing now@0.7.0     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing now@0.7.0     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! node-proxy@0.4.0 install:`make`
nodester npm ERR!`sh "-c" "make"` failed with 2
nodester npm ERR! 
nodester npm ERR! Failed at the node-proxy@0.4.0 install script.
nodester npm ERR! This is most likely a problem with the node-proxy package,
nodester npm ERR! not with npm itself.
nodester npm ERR! Tell the author that this fails on your system:
nodester npm ERR!     make
nodester npm ERR! You can get their info via:
nodester npm ERR!     npm owner ls node-proxy
nodester npm ERR! There is likely additional logging output above.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.11-83.9.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "now"
nodester npm ERR! cwd /node/app/redacted/3550-525aa2e1aa83ea228e10d6c905de4d0b_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.18
nodester npm ERR! 
# nodester npm not ok

**Comment by yocontra** [comment]
Chris is migrating everything to some new disks AFAIK because we ran out of room, should be fixed once that is done

**Comment by stevebrownlee** [comment]
Thanks for the update!

**Comment by shwaydogg** [comment]
Thanks for the nodester invite!  I had my project up and running.  It was not updating after my git pushes though, so I was uninstalling and re-installing the app to update (not often).  

This was working fine.  Now  I am getting the same error above as chortlehoort had.  (see my terminal copy below)  I cannot get socket.io to install, but express works fine.

any help or indication if this is a problem with nodester or my code would be very much appreciated!!!!

thanks!

---

07:29 PM $$ nodester npm install amaze expressnodester info installing to app: amaze
nodester
07:29 PM $$ nodester npm install amaze expressnodester info installing to app: amaze
nodester info installing these npm packages: express
nodester ├── mime@1.2.4
nodester ├── qs@0.4.2r
nodester ├── mkdirp@0.3.0
nodester └── connect@1.8.6
nodester 

nodester warn you should restart your app after you are finished installing packages.

07:29 PM $$ nodester npm install amaze socket.ionodester info installing to app: amaze
nodester info installing these npm packages: socket.io
nodester > ws@0.4.8 preinstall /node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
nodester > make
nodester node-waf configure build
nodester Checking for program g++ or c++          : /usr/bin/g++ 
nodester Checking for program cpp                 : /usr/bin/cpp 
nodester Checking for program ar                  : /usr/bin/ar 
nodester Checking for program ranlib              : /usr/bin/ranlib 
nodester Checking for g++                         : ok  
nodester Checking for node path                   : not found 
nodester Checking for node prefix                 : ok /usr 
nodester 'configure' finished successfully (0.032s)
nodester Waf: Entering directory `/node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
nodester [1/4] cxx: src/validation.cc -> build/default/src/validation_1.o
nodester [2/4] cxx: src/bufferutil.cc -> build/default/src/bufferutil_2.o
nodester ../src/validation.cc:142: fatal error: error writing to /tmp/ccnJr15I.s: No space left on device
nodester compilation terminated.
nodester ../src/bufferutil.cc:113: fatal error: error writing to /tmp/cc6ZO6VI.s: No space left on device
nodester compilation terminated.
nodester Waf: Leaving directory`/node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
nodester Build failed:
nodester  -> task failed (err #1): 
nodester    {task: cxx validation.cc -> validation_1.o}
nodester  -> task failed (err #1): 
nodester    {task: cxx bufferutil.cc -> bufferutil_2.o}
nodester make: **\* [all] Error 1
nodester npm ERR! error installing ws@0.4.8 Error: ws@0.4.8 preinstall: `make`
nodester npm ERR! error installing ws@0.4.8 `sh "-c" "make"` failed with 2
nodester npm ERR! error installing ws@0.4.8     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing ws@0.4.8     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing ws@0.4.8     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! error installing socket.io-client@0.9.2 Error: ws@0.4.8 preinstall: `make`
nodester npm ERR! error installing socket.io-client@0.9.2 `sh "-c" "make"` failed with 2
nodester npm ERR! error installing socket.io-client@0.9.2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing socket.io-client@0.9.2     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing socket.io-client@0.9.2     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! error installing socket.io@0.9.2 Error: ws@0.4.8 preinstall: `make`
nodester npm ERR! error installing socket.io@0.9.2 `sh "-c" "make"` failed with 2
nodester npm ERR! error installing socket.io@0.9.2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing socket.io@0.9.2     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing socket.io@0.9.2     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! ws@0.4.8 preinstall: `make`
nodester npm ERR! `sh "-c" "make"` failed with 2
nodester npm ERR! 
nodester npm ERR! Failed at the ws@0.4.8 preinstall script.
nodester npm ERR! This is most likely a problem with the ws package,
nodester npm ERR! not with npm itself.
nodester npm ERR! Tell the author that this fails on your system:
nodester npm ERR!     make
nodester npm ERR! You can get their info via:
nodester npm ERR!     npm owner ls ws
nodester npm ERR! There is likely additional logging output above.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io"
nodester npm ERR! cwd /node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! code ELIFECYCLE
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw/npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.

07:29 PM $$ nodester npm list amazenodester info list npm packages for app: amaze
nodester └─┬ express@2.5.8 
nodester   ├─┬ connect@1.8.6 
nodester   │ └── formidable@1.0.9 
nodester   ├── mime@1.2.4 
nodester   ├── mkdirp@0.3.0 
nodester   └── qs@0.4.2 
nodester 
 info installing these npm packages: express
nodester ├── mime@1.2.4
nodester ├── qs@0.4.2
nodester ├── mkdirp@0.3.0
nodester └── connect@1.8.6
nodester 

nodester warn you should restart your app after you are finished installing packages.
07:29 PM /home/shwaydogg/Documents/HackerSchool/aMAZEing 
07:29 PM /home/shwaydogg/Documents/HackerSchool/aMAZEing 
07:29 PM /home/shwaydogg/Documents/HackerSchool/aMAZEing 
07:29 PM /home/shwaydogg/Documents/HackerSchool/aMAZEing nodester npm install amaze socket.ionodester info installing to app: amaze
nodester info installing these npm packages: socket.io
nodester > ws@0.4.8 preinstall /node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
nodester > make
nodester node-waf configure build
nodester Checking for program g++ or c++          : /usr/bin/g++ 
nodester Checking for program cpp                 : /usr/bin/cpp 
nodester Checking for program ar                  : /usr/bin/ar 
nodester Checking for program ranlib              : /usr/bin/ranlib 
nodester Checking for g++                         : ok  
nodester Checking for node path                   : not found 
nodester Checking for node prefix                 : ok /usr 
nodester 'configure' finished successfully (0.032s)
nodester Waf: Entering directory `/node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
nodester [1/4] cxx: src/validation.cc -> build/default/src/validation_1.o
nodester [2/4] cxx: src/bufferutil.cc -> build/default/src/bufferutil_2.o
nodester ../src/validation.cc:142: fatal error: error writing to /tmp/ccnJr15I.s: No space left on device
nodester compilation terminated.
nodester ../src/bufferutil.cc:113: fatal error: error writing to /tmp/cc6ZO6VI.s: No space left on device
nodester compilation terminated.
nodester Waf: Leaving directory`/node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
nodester Build failed:
nodester  -> task failed (err #1): 
nodester    {task: cxx validation.cc -> validation_1.o}
nodester  -> task failed (err #1): 
nodester    {task: cxx bufferutil.cc -> bufferutil_2.o}
nodester make: **\* [all] Error 1
nodester npm ERR! error installing ws@0.4.8 Error: ws@0.4.8 preinstall: `make`
nodester npm ERR! error installing ws@0.4.8 `sh "-c" "make"` failed with 2
nodester npm ERR! error installing ws@0.4.8     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing ws@0.4.8     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing ws@0.4.8     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! error installing socket.io-client@0.9.2 Error: ws@0.4.8 preinstall: `make`
nodester npm ERR! error installing socket.io-client@0.9.2 `sh "-c" "make"` failed with 2
nodester npm ERR! error installing socket.io-client@0.9.2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing socket.io-client@0.9.2     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing socket.io-client@0.9.2     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! error installing socket.io@0.9.2 Error: ws@0.4.8 preinstall: `make`
nodester npm ERR! error installing socket.io@0.9.2 `sh "-c" "make"` failed with 2
nodester npm ERR! error installing socket.io@0.9.2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
nodester npm ERR! error installing socket.io@0.9.2     at ChildProcess.emit (events.js:67:17)
nodester npm ERR! error installing socket.io@0.9.2     at ChildProcess.onexit (child_process.js:192:12)
nodester npm ERR! ws@0.4.8 preinstall: `make`
nodester npm ERR! `sh "-c" "make"` failed with 2
nodester npm ERR! 
nodester npm ERR! Failed at the ws@0.4.8 preinstall script.
nodester npm ERR! This is most likely a problem with the ws package,
nodester npm ERR! not with npm itself.
nodester npm ERR! Tell the author that this fails on your system:
nodester npm ERR!     make
nodester npm ERR! You can get their info via:
nodester npm ERR!     npm owner ls ws
nodester npm ERR! There is likely additional logging output above.
nodester npm ERR! 
nodester npm ERR! System Linux 2.6.35.14-106.53.amzn1.x86_64
nodester npm ERR! command "node" "/usr/bin/npm" "install" "socket.io"
nodester npm ERR! cwd /node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw
nodester npm ERR! node -v v0.4.9
nodester npm ERR! npm -v 1.0.106
nodester npm ERR! code ELIFECYCLE
nodester npm ERR! 
nodester npm ERR! Additional logging details can be found in:
nodester npm ERR!     /node/app/shwaydogg/7681-bc3007fb56dc61d25b9a7a95c8b785ac_rw/npm-debug.log
nodester npm not ok

nodester warn you should restart your app after you are finished installing packages.
07:29 PM /home/shwaydogg/Documents/HackerSchool/aMAZEing nodester npm list amazenodester info list npm packages for app: amaze
nodester └─┬ express@2.5.8 
nodester   ├─┬ connect@1.8.6 
nodester   │ └── formidable@1.0.9 
nodester   ├── mime@1.2.4 
nodester   ├── mkdirp@0.3.0 
nodester   └── qs@0.4.2 
nodester
