### ISSUE TITLE
App Already Running

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester-cli#29]
nodester app create and nodester app init successfully creates, deploys, and runs app but the CLI returns an error stating that the app is already running.  It tries to restart the app even though the push from git will have started the app.

nodester app init amiup
nodester info initializing git repo for amiup into folder amiup
nodester info cloning the repo git clone git@nodester.com:/node/git/topher/3642-e271cc6feacc8497f80f870b013f3229.git amiup
nodester info clone complete
nodester info Writing app data to config in amiup/.nodester.appconfig
nodester info writing app files
nodester info processing the initial commit
nodester info attemping to start the new app.
nodester ERROR [HTTP 408] failure - application already running.

**Comment by yocontra** [comment]
Fixed in 29a8a1bbfb80fd5c4ad25e76d00227eb28a326e5
