### ISSUE TITLE
Graceful outcome for app init on existing repo

### ISSUE THREAD

**Issue by martypdx** [nodester/nodester-cli#30]
Creating a nodester app for existing repo then running nodester app init clobbers existing server.js and does other damage, and then pushes those changes to github as well.

Looking for a kinder, gentler app init.

**Comment by yocontra** [comment]
I'll write an app recreate/reinit commands that don't touch the server and clone from it instead, yeah?

**Comment by martypdx** [comment]
I think ideal would be to have app init just work, and only add what is necessary. I don't know what the total body of work is, but just look at what I have now in the directory, I would say that it should not have added server.js since it already existed.

Since git repo already existed, it should have just added nodester as a repo (which it did) and added .nodester.appconfig. It shouldn't do a push to origin (which in this case was on github). I created another test app "from scratch" and noticed it added the nodester repo as origin, so maybe that's why?

Anyway, I think the end goal is that people are going to have existing repo's and doing an app init should be safe and should only add the pieces necessry.

**Comment by yocontra** [comment]
Ah I see what you're getting at now, I misunderstood you before. Still very doable, will only require a few minor changes for each command to check if the file exists and prompt for an overwrite. Thanks for elaborating

**Comment by martypdx** [comment]
Yeah, just had a chance to look at app.js and init method seems like changes would be straight-forward.

(btw - nice work getting the security stuff and cli stuff squared up. it works like a champ, and I'm working under Cygwin on Windows!)

**Comment by yocontra** [comment]
Can you confirm this is still an issue? A lot has been updated
