### ISSUE TITLE
Cannot change appfile

### ISSUE THREAD

**Issue by tlianza** [nodester/nodester-cli#32]
I have failed via googling, reading the docs, and poking through the various commands of the built-in nodester-cli help to figure out how to do something I expect is incredibly simple.

How do you change your app's appfile?

Sorry, I know this is a super-basic function and it's probably very obvious to everyone how it's done, but I'd suggest writing it down somewhere.

**Comment by yocontra** [comment]
As flawed as it may seem, `nodester app create <name> <start file>` is the only way to do it right now. I can assure you this will be fixed in V2. If create doesn't complete you might have to delete it first.

**Comment by wishpot** [comment]
So, another dumb question... does app delete remove your git repo? 

For anyone using express.js, which seems to be common, the default start file (app.js) has a different name than nodester's default (server.js).  So, I assume a lot of people have run into this.

**Comment by tlianza** [comment]
Just in case, I backed it up, then issued a delete... but it doesn't work - times out.  Error if I try to re-create as well.

```
nodester warn Are you sure you want to do this?
     Waiting 10 seconds before continuing, Ctrl+C to abort)
...........
nodester warn Really deleting app now, you were warned..
nodester ERRO socket hang up
```

**Comment by yocontra** [comment]
Can you confirm this issue is still occurring? I applied a fix

**Comment by rauno56** [comment]
Deleting works. Recreating works.
