### ISSUE TITLE
App Delete, Domain Delete, and GitReset Not Working

### ISSUE THREAD

**Issue by chrismatthieu** [nodester/nodester-cli#33]
I fixed the API and updated the docs. The issue was with passing params via the DELETE verb. Apparently the params need to be included in the URL like this:

curl -X DELETE -u "testuser:123" http://api.nodester.com/app/appname
curl -X DELETE -u "testuser:123" http://api.nodester.com/gitreset/appname
curl -X DELETE -u "testuser:123" http://api.nodester.com/appdomains/appname/domain

**Comment by yocontra** [comment]
Fixed.
