### ISSUE TITLE
npm install nodester-cli permission denied

### ISSUE THREAD

**Issue by jgoodall** [nodester/nodester-cli#34]
npm is failing with a permission error when trying to install nodester-cli on mac os x, 10.7.2. this is strange because the folders in question are owned by me, but the 'lib' directory (/var/folders/ ... /___package.npm/package/lib/) referred to below is empty; there is no nodester.js file in the lib folder.

npm log:

npm http GET https://registry.npmjs.org/nodester-cli
npm http 304 https://registry.npmjs.org/nodester-cli
npm http GET https://registry.npmjs.org/nodester-api
npm http GET https://registry.npmjs.org/colors/0.3.0
npm http GET https://registry.npmjs.org/iniparser/1.0.1
npm http 304 https://registry.npmjs.org/iniparser/1.0.1
npm http 304 https://registry.npmjs.org/colors/0.3.0
npm http 304 https://registry.npmjs.org/nodester-api
npm http GET https://registry.npmjs.org/nodester-api/-/nodester-api-0.1.22.tgz
npm http 200 https://registry.npmjs.org/nodester-api/-/nodester-api-0.1.22.tgz

npm ERR! Error: EACCES, permission denied '/var/folders/v1/31_sywnx1jl_0q294byxm879c4c5b7/T/npm-1329136873298/1329136873298-0.002972597721964121/___package.npm/package/lib/nodester.js'
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "nodester-cli" "-g"
npm ERR! cwd /Users/ojg
npm ERR! node -v v0.6.10
npm ERR! npm -v 1.1.1
npm ERR! path /var/folders/v1/31_sywnx1jl_0q294byxm879c4c5b7/T/npm-1329136873298/1329136873298-0.002972597721964121/___package.npm/package/lib/nodester.js
npm ERR! code EACCES
npm ERR! message EACCES, permission denied '/var/folders/v1/31_sywnx1jl_0q294byxm879c4c5b7/T/npm-1329136873298/1329136873298-0.002972597721964121/___package.npm/package/lib/nodester.js'
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ojg/npm-debug.log
npm not ok

**Comment by yocontra** [comment]
`sudo npm install nodester-cli -g`

This is standard npm stuff - anything with -g requires sudo.
