### ISSUE TITLE
Password does not accept non-alphanumeric characters

### ISSUE THREAD

**Issue by jkirkpatrick** [nodester/nodester-cli#47]
When resetting my password via the command line, any password that includes any non-alphanumeric characters is not accepted.

nodester user setpass ...token... MyNewPassword!!!

nodester ERROR Fatal Error! API Response: {"status":"failure","messages":"No such token"}
Reason: HTTP Error 404 returned.

Using the SAME token again (without the exclamation at the end) :

nodester user setpass ...token... MyNewPassword

nodester info password successfully changed.
nodester info writing user data to config

**Comment by alejandro** [comment]
@jkirkpatrick I'll take a look at this. It should work, though. Mine has a non-alphanumeric char ;)
