### ISSUE TITLE
Permission denied when trying to install packages for project

### ISSUE THREAD

**Issue by scan** [nodester/nodester-cli#51]
For my newly started nodester project to work, of course, the npm packages have to be installed. But every time I try, nodester tells me `permission denied`:

```
$ nodester npm install ponyville
nodester info grabbing dependencies from package.json...
nodester info installing to app: ponyville
nodester info installing these npm packages: coffee-script@>= 1.3 <1.4,connect,connect-redis,connect-assets,express@<3,hiredis,jade,less,moment,nib,now,redis,socket.io,stylus,underscore,underscore.string
nodester /bin/sh: line 0: cd: /node/app/scan/11937-2e3632b5ea65957b341f3566f3ad8c10_rw: No such file or directory
nodester /bin/sh: =: Permission denied

nodester info Dependencies installed
nodester info Attemping to restart app: ponyville
nodester warn false
```

I suspect it comes from the `coffee-script@>= 1.3 <1.4` part. It seems this is not being escaped when put into the `npm` shell command.

**Comment by scan** [comment]
I think this is related to Issue #50, because of obsolete npm.

**Comment by alejandro** [comment]
Not really. This is because the setup process failed. Try to setup everything again and it should work.
