### ISSUE TITLE
nodester app create $name does not display port

### ISSUE THREAD

**Issue by abraham** [nodester/nodester-cli#7]
I created an app with the cli and the success message didn't contain the port. Running OSX 10.6.6, `nodester-api@0.1.5` and `nodester-cli@0.2.3`.

```
$ nodester app create intersect-staging
nodester info Checking config..
nodester info creating app: intersect-staging server.js
nodester info successfully created app intersect-staging to will run on port  from server.js
```

**Comment by davglass** [comment]
This is fixed in master, I don't have access to deploy a new version yet, but it will be soon I hope..

**Comment by abraham** [comment]
Awesome. Works for me.
